Vagrant.configure(2) do |config|

    config.vagrant.plugins = ["vagrant-vbguest"]
    config.vbguest.auto_update = true
    config.ssh.insert_key = true
    config.vm.define "lovspotify" do |system|
        system.vm.network "public_network"
        system.vm.network "forwarded_port", guest: 22, host: 5557
        system.vm.network "forwarded_port", guest: 8080, host: 8080
        system.vm.box = "ubuntu/bionic64"

        system.vm.hostname = "lovspotify"
           system.vm.provider :virtualbox do |vb|
             vb.name = "lovspotify"
             vb.gui = false
             vb.memory = 4096
             vb.cpus = 2

           end
        end
        config.vm.synced_folder "../", "/home/vagrant/workspace", type: "virtualbox"
        config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
        config.vm.provision :shell, :path => "./bootstrap.sh"
    end
