Document: lovspotify
Title: Debian lovspotify Manual
Author: Thorsten H
Abstract: This manual describes what lovspotify is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lovspotify/lovspotify.sgml.gz

Format: postscript
Files: /usr/share/doc/lovspotify/lovspotify.ps.gz

Format: text
Files: /usr/share/doc/lovspotify/lovspotify.text.gz

Format: HTML
Index: /usr/share/doc/lovspotify/html/index.html
Files: /usr/share/doc/lovspotify/html/*.html
